### ISSUE TITLE
这个能否直接输出图片原本地址，而不是输出一个下载的地址？

### ISSUE THREAD

**Issue by tangzhehao** [jysperm/RPUP#1]
RT

**Comment by jysperm** [comment]
可以考虑删去 [index.php 102 - 103](https://github.com/jysperm/RPUP/blob/master/index.php#L102) 行，然后按照 [mime_content_type](http://php.net/manual/en/function.mime-content-type.php) 这个页面提供的方法发送正确的 content-type

**Comment by tangzhehao** [comment]
但是文件结尾应该还是没有后缀的吧？小的是新手，问些智障问题请大神谅解。

**Comment by jysperm** [comment]
url 里有没有后缀是无所谓的，只要 content-type 正确就好。
